/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.example.scala.wordcount

import org.apache.spark.SparkContext
import org.apache.spark.SparkConf

object App {
  def main(args: Array[String]) : Unit =  {
    // println(greeting())
    val conf = new SparkConf().setAppName("Word Counter")
    val sc = new SparkContext(conf)
    val textFile = sc.textFile("file:///usr/local/Cellar/apache-spark/3.1.1/README.md")
    val tokenizedFileData = textFile.flatMap(line=>line.split(" "))
    val countPrep = tokenizedFileData.map(word=>(word, 1))
    val counts = countPrep.reduceByKey((accumValue, newValue)=>accumValue + newValue)
    val sortedCounts = counts.sortBy(kvPair=>kvPair._2, false)
    println(sortedCounts)
    sortedCounts.saveAsTextFile("file:///Users/devnull/data/ReadMeWordCountViaApp")
    
  }

  def greeting(): String = "Hello, world!"
}
